"""new fileds in user model

Revision ID: 32d953ddb883
Revises: d3cb74857189
Create Date: 2020-02-23 14:04:19.285572

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '32d953ddb883'
down_revision = 'd3cb74857189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
